/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xemay.view;

/**
 *
 * @author PC
 */
public class ThongKeXeBanChayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeXeBanChayJPanel
     */
    public ThongKeXeBanChayJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuanLyNhanVien4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        cboTimKiem13 = new javax.swing.JComboBox<String>();
        cboTimKiem14 = new javax.swing.JComboBox<String>();
        jButton37 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        QuanLyNhanVien4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("BÁO CÁO THỐNG KÊ");

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setMinimumSize(new java.awt.Dimension(6, 35));

        jButton36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton36.setText("Tìm kiếm");

        jTable13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TOP", "Mã Xe", "Tên Xe", "Số Lượng", "Doanh Thu", "Lợi Nhuận"
            }
        ));
        jTable13.setRowHeight(30);
        jScrollPane13.setViewportView(jTable13);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel39.setText("Xe bán chạy nhất");

        cboTimKiem13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboTimKiem13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tháng", " " }));
        cboTimKiem13.setMinimumSize(new java.awt.Dimension(138, 35));

        cboTimKiem14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboTimKiem14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Năm" }));
        cboTimKiem14.setMinimumSize(new java.awt.Dimension(138, 35));

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton37.setText("In thống kê");

        javax.swing.GroupLayout QuanLyNhanVien4Layout = new javax.swing.GroupLayout(QuanLyNhanVien4);
        QuanLyNhanVien4.setLayout(QuanLyNhanVien4Layout);
        QuanLyNhanVien4Layout.setHorizontalGroup(
            QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhanVien4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(QuanLyNhanVien4Layout.createSequentialGroup()
                            .addComponent(cboTimKiem14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(cboTimKiem13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 1715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 114, Short.MAX_VALUE))
            .addGroup(QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuanLyNhanVien4Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel33)
                    .addContainerGap(1628, Short.MAX_VALUE)))
        );
        QuanLyNhanVien4Layout.setVerticalGroup(
            QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyNhanVien4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addGroup(QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTimKiem13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTimKiem14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(QuanLyNhanVien4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuanLyNhanVien4Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel33)
                    .addContainerGap(897, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1898, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(QuanLyNhanVien4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(QuanLyNhanVien4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyNhanVien4;
    private javax.swing.JComboBox<String> cboTimKiem13;
    private javax.swing.JComboBox<String> cboTimKiem14;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTable jTable13;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
